### PR TITLE
Support pinning to specific commits

### LINKED ISSUE #144: Pin to a commit
It'd be useful if we can pin plugins to a specific commit. I had some plugins break because of an update and I now have no way to pin or rollback to a working commit.

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #144

Useful to fix breakages or to stick to audited versions of a plugin

### CODE REVIEW

**Comment by jandamm** [comment]
Thank you for taking on this long standing issue, @hauntsaninja! 

I'll test the PR a bit and merge it soon 👍

**Comment by jandamm** [comment]
Hey @hauntsaninja,

works good.
I only removed a debug print and updated the api a bit.

So instead of assuming that a "branch" which matches a commit hash is a pinning you now need to provide an explicit `--pin`.
This will then check whether the "branch" is a full commit hash and will throw an error if not.

What do you think?

**Comment by hauntsaninja** [comment]
Nice, that sounds good to me!

It could be nice to still have that print statement (it was behind an env var). I used this to easily replace all my `zgen load` with pinned equivalents. But maybe the better UI is having some separate top-level command, I just wasn't sure how to discover what exactly gets loaded otherwise.

**Comment by jandamm** [comment]
We could mark the pinned repos by adding `.git/.zgenom-pinned`.
Then we could provide an api with `zgenom list --{un,}pinned` which checks for those files.
Or we use the `symbolic-ref` you used in `zgenom-update`.

**Comment by hauntsaninja** [comment]
Ah no, the use case is say my `.zshrc` does:
```
zgenom load u/r1
zgenom load u/r2 file
zgenom load u/r3 file branch
```
And then I want to make my current setup completely reproducible. Instead of going through one by one and figuring out hashes, I can just reset and run with debug print, and copy paste to get
```
zgenom load u/r1 . sha
zgenom load u/r2 file sha
zgenom load u/r3 file sha
```
Probably makes more sense for this to be some sort of top-level zgenom command, like `zgenom lock`. But wasn't exactly sure how to go about implementing that.

**Comment by jandamm** [comment]
Ah you want to print all currently checked out hashes?

```zsh
> zgenom list --sha
user1/repo 1a3...
user2/repo 3ba...
```

**Comment by jandamm** [comment]
If you want to print the full setup code printed it might also be feasible to write this as a plugin (e.g. `zgenom-ext-lock`)
See https://github.com/jandamm/zgenom?tab=readme-ov-file#extensions.
After a `zgenom reset` `$ZGEN_LOADED` is set to all loaded files and `$ZGENOM_LOADED` is set to all `user/repo`s.

**Comment by hauntsaninja** [comment]
Oh perfect, that will work well. Thanks for landing this and for zgenom!

**Pull request merged**
