### PR TITLE
Added last update and init.zsh to .gitignore

### PR DESCRIPTION
**Pull request by Lenart12**

### CODE REVIEW

**Comment by jandamm** [comment]
Hey @Lenart12,

thank you for your contribution!

Those files shouldn't actually be in the root folder of `zgenom`.
`init.zsh` and `.zgenom-*-lastupdate` should be in `$ZGEN_DIR` which is by default the already ignored `sources` folder.
If you've set `$ZGEN_DIR` manually to the root folder of the git project all your plugins should be in the same folder as well.

The files `.zgen_*_lastupdate` are from a short transition period and are superseded by the `.zgenom-*` ones. They can safely be removed too.
They could also be created by https://github.com/unixorn/autoupdate-zgenom or https://github.com/unixorn/autoupdate-zgen. This functionality is now integrated into `zgenom`.

Can you please check if `$ZGEN_DIR` is set to the "git root" and if those files were modified recently? Because they shouldn't actually be there.

**Comment by Lenart12** [comment]
Yes, you are correct. I cloned this repo as `.zgenom` since I want it to be hidden, looks like this makes it clash with this and plugins just like you said. I think its good if they are in gitignore anyways.

**Comment by jandamm** [comment]
Cloning it into `~/.zgenom` shouldn't be an issue.
Then the files should be in `~/.zgenom/sources`.

Have you set `$ZGEN_DIR` yourself?
As far as I know https://github.com/unixorn/zsh-quickstart-kit sets `ZGEN_DIR=$HOME/.zgenom`.

**Comment by Lenart12** [comment]
Yes, then this was caused by quickstart kit, I did use it.

**Comment by jandamm** [comment]
Yeah it's unfortunate that the quickstart kit sets `$ZGEN_DIR`. While this was useful for `zgen` it's not really needed for `zgenom`.
But it's not easy to just unser the variable since this would result in cloning all plugins again or a migration has to be done.

Do you still use the quickstart kit?

**Comment by Lenart12** [comment]
Thanks for the info 😊. Yes I still use it.

**Comment by jandamm** [comment]
Did you try `zgenom` without the quickstart kit?
Since the kit already installs `zgenom` to `~/.zqs-zgenom` and uses `~/.zgenom` as folder for the sources.

**Comment by Lenart12** [comment]
No, I installed it before because I didn't know it would autoinstall it in the kit. Not a real issue then, could close this PR

**Pull request closed without merging**
