### PR TITLE
Add automatic plugin and selfupdate functions

### LINKED ISSUE #56: Add autoupdate functionality
Moving this to a new issue.

I like the idea of having the autoupdate being part of core, defaulting to off. I also like the idea of moving things into a bindir and having the things in there not even get sourced unless `ZGENOM_LOAD_XYZ` is set to minimize startup impact.

I don't really know how autoload functions work all that well, that might be enough of a performance saver to go with that over not sourcing unused functionality.

### PR DESCRIPTION
**Pull request by unixorn**
- Add autoupdate functionality as separate commands for updating `zgenom` and/or the user's plugins to give users more control of what gets updated how frequently.

  - Add `zgen autoupdate-system INTEGER_DAYS` to update zgenom if it's been longer than INTEGER_DAYS since the last check
  - Add `zgen autoupdate-plugins INTEGER_DAYS` to update the user's plugins if it's been longer than INTEGER_DAYS since the last check
  - Add `zgen autoupdate INTEGER_DAYS` to update both if it's been longer than INTEGER_DAYS since the last check - this is what most users will opt for
  - `zgenom update` and `zgenom selfupdate` both now update the receipt files used by the `zgen autoupdate-{system,plugins}` functions so they're aware of when updates were checked

Closes #56

### CODE REVIEW

**Comment by unixorn** [comment]
@jandamm - this is pretty much a straight import of the plugin code, with some cleanups to update `ZGEN` to `ZGENOM` in variable names. I still need to do some test runs and will convert it from draft once that's done, but I wanted to push the WIP in case you had suggestions to improve it.

**Comment by jandamm** [comment]
Nice, I'll have a look later.

**Comment by jandamm** [comment]
Hey @unixorn,
looks good so far.
For now I kept the `-zgen-...` prefix for "private" functions.

What do you think about setting the according date when executing `zgenom update` or `zgenom selfupdate`?
I'd lean towards not auto-updating when the user executed `zgenom update` the day before.

For ease of use I'd also add `zgenom autoupdate` which calls `system` and `plugins`. My guess would be that most users update both.

**Comment by unixorn** [comment]
Agreed - I'll add a combined `zgenom autoupdate` and also make `zgenom update` and `zgenom selfupdate` update the appropriate receipt files.

**Comment by unixorn** [comment]
Oh, and I'll make `zgenom autoupdate` update zgenom before it updates the plugins, just in case there are code changes that could affect the plugin update like when you added support for non-master branches.

**Comment by jandamm** [comment]
In the current design a new shell has to be started in order to use the updated zgenom version.

Also `zgenom autoupdate` will only taken into account when the next shell is started.
So maybe it would be feasible to dispatch `autoupdate` in a background shell?
Or it could be waited and a new shell started afterwards (eg `zsh -il ; exit`)

In my dotfiles I create a new shell and update zgenom. Then create another shell and update all plugins. Afterwards I create a new login shell (which creates a new `init.zsh`). When I start a new shell at some point I've got a new and initialized shell.
In theory this could all be done in the background or the new shell could be used.

**Comment by unixorn** [comment]
I'm going to test it as-is later today, then play around with making the selfupdate load and swap shells.

Unless you think we should get this merged, then update the selfupdate functionality in a separate PR?

**Comment by jandamm** [comment]
Nothing wrong with packing everything into one PR 👍

**Comment by jandamm** [comment]
Hey @unixorn,

how's it going with this PR?

I'd like to start with the refactoring and ideally this PR would be merged before. Otherwise it will create merge conflicts.
Maybe we first integrate the feature and the have a look how to improve it?

**Comment by unixorn** [comment]
I've been busy and honestly forgot about this - I'll take a look this weekend, but I think it's in a working state, it just needs some testing.

**Comment by jandamm** [comment]
I've fixed a few little errors and the feature now looks good.

For now I've disabled the standalone `zgenom autoupdate-system` and `zgenom autoupdate-plugin` since I want to provide them as e.g. `zgenom autoupdate --plugin`.

Also there is a bug which causes all plugins to be loaded twice.
```zsh
source zgenom.zsh # calls zgenom init
zgenom autoupdate 7 # calls zgenom reset (if zgenom save is called as before the init.zsh is empty)
if ! zgenom saved; then 
    # loads all plugins
fi
```

**Pull request merged**
