### PR TITLE
Add basic help functionality

### PR DESCRIPTION
**Pull request by kylo252**
Provides a help message in the following situations:
- Using `zgenom help`
- Using `zgenom` without any arguments
- Using `zgenom` with an invalid argument

### CODE REVIEW

**Comment by jandamm** [comment]
Thanks for your contribution.
I'll test and merge it tomorrow 👍

**Comment by jandamm** [comment]
Looks good, like it 👍
Maybe we should remove `completion` since it is deprecated?

**Comment by kylo252** [comment]
> Looks good, like it 👍
> Maybe we should remove `completion` since it is deprecated?

Remove it from both files `_zgen` and `zgen.zsh`? 


I initially wanted to implement some sort of `getopts` parser, but I realized after a while that it would basically result in a rather substantial refactoring. Maybe it can be done incrementally for newer commands, but I'm not quite sure if it's going against the "simplicity" concept of the tool. 

It would however offer a much better error handling mechanisms, and lower the entry-point to allow broader audience with the help of a detailed help output.

**Comment by jandamm** [comment]
> Remove it from both files _zgen and zgen.zsh?

Yes, I think removing it from both is safe.

I wouldn't want to break compatibility with `zgen` (at least not for now) - meaning valid `zgen` code should just work in `zgenom` as well.

It would be interesting how users add new plugins.
I have a refactoring of the completion on my agenda which might help the interactive approach.
But it's also a bit unfortunate to have to use `.` as a location since it is required before providing a branch. (`zgenom load <repo> . <branch>`)

Another idea would be to separate the `zgen` and `zgenom` apis and use `zgenom load <repo> -b master` while the `zgen load <repo> . master` is the legacy api.
Or add it as a optional api (if it matches `^zgenom [a-z]+ -` the new api is used).

**Comment by kylo252** [comment]
I thought I could do it directly on GitHub but ended up with two seperate commits, so I squashed them together and did a force push. Sorry about the confusion :)

> Another idea would be to separate the `zgen` and `zgenom` apis 

Yeah that's what I thought of as well. But maybe I should've explained more that I think it would get hacky pretty quickly to maintain two different option parsers especially if they're concerned with the same functions/options. 

> and use `zgenom load <repo> -b master` while the `zgen load <repo> . master` is the legacy api.

It's a lot easier to just print what the parser is expecting rather than keep a separate "help" messages for `load`, not to mention you need logic to detemine which version did they user mean. I would probably introduce new signatures and deprecate the old ones slowly but surely. I think that would be less of a headache imo.

**Comment by jandamm** [comment]
Thanks for your contribution.
I'll create a discussion for the improved parsing. It isn't actually this much work since all existing commands use the same order: `<repo> [dir] [branch] ...` where only `...` differs depending on the command.

**Pull request merged**
